import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  openGraph: {
    title: 'QuantumX-24',
    description: 'Generated by Ananda Krishnan Nair',
    siteName: 'QuantumX',
    images: [
      {
        url: '/logo.png',
        width: 800,
        height: 600,
      },
      {
        url: '/logo.png',
        width: 1800,
        height: 1600,
        alt: 'QX',
      },
    ],
    locale: 'en_US',
    type: 'website'
  },
  manifest: '/manifest.json'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
