import bestManagerImg from '../images/best-manager.png'
import aquaRushImg from '../images/aqua-rush.png'
import botsRoyaleImg from '../images/bots-royale.png'
import byteBrawlImg from '../images/byte-brawl.png'
import conclaveImg from '../images/conclave.png'
import droneRaceImg from '../images/drone-race.png'
import chaiPeCharchaImg from '../images/chai-pe-charcha.png'
import circuitPremierLeagueImg from '../images/circuit-premier-league.png'
import cybercodeImg from '../images/cybercode.png'
import debateImg from '../images/debate.png'
import forumImg from '../images/forum.png'
import goKartRaceImg from '../images/go-kart-race.png'
import innovatorsImg from '../images/innovators.png'
import lineRoboChallengeImg from '../images/line-robo-challenge.png'
import olympiadImg from '../images/olympiad.png'
import pitchersImg from '../images/pitchers.png'
import quantumHacksImg from '../images/quantum-hacks.png'
import questJrImg from '../images/quest-jr.png'
import roboFootballImg from '../images/robo-football.png'
import speedSprintImg from '../images/speed-sprint.png'
import streetImg from '../images/street.png'

import byteBrawlDescImg from '../images/byte-brawl-desc.png'
import bestManagerDescImg from '../images/best-manager-desc.png'
import forumDescImg from '../images/forum-desc.png'

export { bestManagerImg, aquaRushImg, botsRoyaleImg, byteBrawlImg, conclaveImg, droneRaceImg, chaiPeCharchaImg, circuitPremierLeagueImg, cybercodeImg, debateImg, forumImg, goKartRaceImg, innovatorsImg, lineRoboChallengeImg, olympiadImg, pitchersImg, quantumHacksImg, questJrImg, roboFootballImg, speedSprintImg, streetImg, byteBrawlDescImg, bestManagerDescImg, forumDescImg }