import { aquaRushDescImg, aquaRushImg, bestManagerDescImg, bestManagerImg, botsRoyaleDescImg, botsRoyaleImg, byteBrawlDescImg, byteBrawlImg, chaiPeCharchaDescImg, chaiPeCharchaImg, circuitPremierLeagueDescImg, circuitPremierLeagueImg, conclaveDescImg, conclaveImg, cybercodeDescImg, cybercodeImg, debateDescImg, debateImg, droneRaceDescImg, droneRaceImg, forumDescImg, forumImg, innovatorsDescImg, innovatorsImg, lineRoboChallengeDescImg, lineRoboChallengeImg, olympiadDescImg, olympiadImg, pitchersDescImg, pitchersImg, quantumHacksDescImg, quantumHacksImg, questJrDescImg, questJrImg, roboFootballDescImg, roboFootballImg, speedSprintDescImg, speedSprintImg, streetDescImg, streetImg } from '@/utils/event-images'


export const eventsData = [
    {
        id: "QX_EV_01",
        name: "Aqua Rush",
        img: aquaRushImg,
        imgDesc: aquaRushDescImg,
        desc: "Prepare to be captivated by the thrilling spectacle of the RC Boat Race, where miniature speedsters navigate the aquatic arena with precision and agility.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 300,
        prizePool: 15000,
        location: "Sports Ground, NHCE.",
        ruleBook: ""
    },
    {
        id: "QX_EV_02",
        name: "Best Manager",
        img: bestManagerImg,
        imgDesc: bestManagerDescImg,
        desc: "It is a dynamic arena of unique challenges and tasks where managers can showcase their strategic acumen, decision-making prowess, and innovative leadership skills. This immersive competition will test the mettle of participants, demanding quick thinking, strategic planning, and effective communication.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 400,
        prizePool: 12000,
        location: "Chanakya Seminar Hall, NHC",
        ruleBook: ""
    },
    {
        id: "QX_EV_03",
        name: "Bots Royale",
        img: botsRoyaleImg,
        imgDesc: botsRoyaleDescImg,
        desc: "It is a combat robotics competition in which teams design, build, and operate remote-controlled robots to fight in an arena combat elimination tournament. The robots are armed with a variety of weapons, such as hammers, saws, and blades, and the goal is to disable or destroy the opponent's robot.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 5,
        fee: 1000,
        prizePool: 130000,
        location: "Basketball Quadrangle, NHCE",
        ruleBook: ""
    },
    {
        id: "QX_EV_04",
        name: "Byte Brawl",
        img: byteBrawlImg,
        imgDesc: byteBrawlDescImg,
        desc: "Immerse yourselves in the world of Battlegrounds Mobile India (BGMI) and Call of Duty (COD), two of the most popular and adrenaline-fueled games in existence.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        prizePool: 10000,
        location: "C203, NHCE",
        ruleBook: ""
    },
    {
        id: "QX_EV_05",
        name: "Chai Pe Charcha",
        img: chaiPeCharchaImg,
        imgDesc: chaiPeCharchaDescImg,
        desc: "This summit is a great opportunity to hear from industry experts and learn about the latest advancements in technology. Participants will also have the chance to connect with other people who are interested in technology.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: "",
        prizePool: "",
        location: "Auditorium",
        ruleBook: ""
    },
    {
        id: "QX_EV_06",
        name: "Circuit Premier League",
        img: circuitPremierLeagueImg,
        imgDesc: circuitPremierLeagueDescImg,
        desc: "Delve into the intricate world of embedded systems, assembly language, and hardware mastery. From unravelling coding enigmas to crafting ingenious circuits, participants will be immersed in a day of dynamic challenges and inventive exploration.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 3,
        fee: 500,
        prizePool: 20000,
        location: "ECE Labs, Netaji Subhash Chandra Bose Block, NHCE",
        ruleBook: ""
    },
    {
        id: "QX_EV_07",
        name: "Creator Conclave",
        img: conclaveImg,
        imgDesc: conclaveDescImg,
        desc: "Participants can immerse themselves in a vibrant convergence of artistic visionaries, technological pioneers, and innovative minds as they gather to share their inspiring stories and unveil groundbreaking creations.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: "",
        prizePool: "",
        location: "Auditorium",
        ruleBook: ""
    },
    {
        id: "QX_EV_08",
        name: "CyberCode Quest",
        img: cybercodeImg,
        imgDesc: cybercodeDescImg,
        desc: "This challenge is designed to test the participants' analytical skills and push them to the boundaries of their algorithmic knowledge. They will be confronted with complex problems and must devise innovative solutions.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 200,
        prizePool: 10000,
        location: "MCA Labs, Netaji Subhash Chandra Bose Block, NHCE",
        ruleBook: ""
    },
    {
        id: "QX_EV_09",
        name: "Debate",
        img: debateImg,
        imgDesc: debateDescImg,
        desc: "Calling all eloquent and persuasive speakers! Prepare to engage in intellectual discourse and defend your stance.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 0,
        prizePool: 5000,
        location: "",
        ruleBook: ""

    },
    {
        id: "QX_EV_10",
        name: "Drone Race",
        img: droneRaceImg,
        imgDesc: droneRaceDescImg,
        desc: "Witness the ultimate drone racing competition, where pilots will demonstrate their mastery of control and manoeuvrability amidst challenging courses and breathtaking aerial manoeuvres.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        prizePool: 60000,
        location: "Sports Ground, NHCE",
        ruleBook: "https://docs.google.com/document/d/1LCPIK_pEYlipq52cjDbp4Hnyuh4YfLrM/edit?usp=sharing&ouid=103811776576971983524&rtpof=true&sd=true"

    },
    {
        id: "QX_EV_11",
        name: "Founder's Forum",
        img: forumImg,
        imgDesc: forumDescImg,
        desc: "Participants can engage in stimulating discussions trailblazing founders and experienced mentors about disruptive ideas, scalable solutions, and the transformative journey of transforming visions into successful ventures.",
        date: "",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: "",
        prizePool: "",
        location: "Stage",
        ruleBook: ""
    },
    {
        id: "QX_EV_12",
        name: "",
        img: innovatorsImg,
        imgDesc: innovatorsDescImg,
        desc: "Young Innovators is a dynamic showcase of creativity, where brilliant minds converge to present groundbreaking ideas and pioneering projects. From cutting-edge tech solutions to revolutionary concepts, witness the next generation of innovators shaping tomorrow's world.",
        date: "",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 0,
        prizePool: 5000,
        location: "",
        ruleBook: ""
    },
    {
        id: "QX_EV_13",
        name: "Line Robot Challenge",
        img: lineRoboChallengeImg,
        imgDesc: lineRoboChallengeDescImg,
        desc: "Prepare to test your skills and unleash your creativity at the Line robot Challenge where you'll design, build, and program autonomous robots to navigate a challenging line course.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 300,
        prizePool: 10000,
        location: "Ground Floor, Netaji Subhash Chandra Bose Block, NHCE",
        ruleBook: ""
    },
    {
        id: "QX_EV_14",
        name: "",
        img: olympiadImg,
        imgDesc: olympiadDescImg,
        desc: "Participants will tackle mind-bending puzzles, solve complex problems, and demonstrate their analytical prowess. The Olympiad promises to be an exhilarating spectacle of academic brilliance and strategic manoeuvring.",
        date: "",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 0,
        prizePool: 5000,
        location: "",
        ruleBook: ""
    },
    {
        id: "QX_EV_15",
        name: "Pitchers",
        img: pitchersImg,
        imgDesc: pitchersDescImg,
        desc: "This dynamic platform offers the chance to pitch innovative concepts to a panel of seasoned judges and secure potential investments. Witness the thrill of investment negotiations, creative pitches, and the birth of future enterprises.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 3,
        fee: 1000,
        prizePool: 20000,
        location: "Falconry Hall, Netaji Subhash Chandra Bose Block, NHCE",
        ruleBook: ""
    },
    {
        id: "QX_EV_16",
        name: "Quantum Hacks",
        img: quantumHacksImg,
        imgDesc: quantumHacksDescImg,
        desc: "This is a dynamic arena where collaboration and ingenuity converge to tackle real-world challenges. This immersive event extends beyond mere competition; it's a journey of learning, growth, and the collective pursuit of meaningful impact.",
        date: "24/01/24",
        minSize: 3,
        maxSize: 5,
        fixedSize: null,
        fee: 1000,
        prizePool: 60000,
        location: "Library, Amar Jawan Block, NHCE",
        ruleBook: ""
    },
    {
        id: "QX_EV_17",
        name: "Quest Jr",
        img: questJrImg,
        imgDesc: questJrDescImg,
        desc: "Dive into a world of algorithms, data structures, and problem-solving as you tackle a series of challenging coding tasks. Test your skills against fellow students and experience the thrill of competition.",
        date: "",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 0,
        prizePool: 5000,
        location: "",
        ruleBook: ""
    },
    {
        id: "QX_EV_18",
        name: "Robo Football",
        img: roboFootballImg,
        imgDesc: roboFootballDescImg,
        desc: "Robo Soccer is a captivating competition where teams of autonomous robots engage in a thrilling game of football. This event showcases the culmination of cutting-edge robotics technology, strategic programming, and teamwork, immersing spectators in a world where technology meets sport.",
        date: "24/01/2024",
        minSize: null,
        maxSize: null,
        fixedSize: 2,
        fee: 300,
        prizePool: 15000,
        location: "Basketball Quadrangle, NHCE",
        ruleBook: ""
    },
    {
        id: "QX_EV_19",
        name: "Speed Sprint",
        img: speedSprintImg,
        imgDesc: speedSprintDescImg,
        desc: "Adrenaline-fueled drivers will showcase their mastery of control and manoeuvrability amidst challenging courses and exhilarating speeds.",
        date: "23/01/2024",
        minSize: null,
        maxSize: null,
        fixedSize: 3,
        fee: 300,
        prizePool: 15000,
        location: "Ground, NHCE",
        ruleBook: ""
    }
]


// {
//     id: "QX_EV_20",
//     name: "Hustler's Street",
//     img: streetImg,
//     imgDesc: streetDescImg,
//     desc: "Navigate through a labyrinth of booths showcasing cutting-edge products, services, and solutions from a diverse range of startups. Engage in thought-provoking conversations with passionate founders and industry experts as they delve into the intricacies of their ventures.",
//     date: "23/01/2024",
//     minSize: null,
//     maxSize: null,
//     fixedSize: "",
//     fee: "",
//     prizePool: "",
//     location: "SVM Hostel Corridor",
//     ruleBook: ""
// }