import bestManagerImg from '../images/events/best-manager.png'
import aquaRushImg from '../images/events/aqua-rush.png'
import botsRoyaleImg from '../images/events/bots-royale.png'
import byteBrawlImg from '../images/events/byte-brawl.png'
import conclaveImg from '../images/events/conclave.png'
import droneRaceImg from '../images/events/drone-race.png'
import chaiPeCharchaImg from '../images/events/chai-pe-charcha.png'
import circuitPremierLeagueImg from '../images/events/circuit-premier-league.png'
import cybercodeImg from '../images/events/cybercode.png'
import debateImg from '../images/events/debate.png'
import forumImg from '../images/events/forum.png'
import goKartRaceImg from '../images/events/go-kart-race.png'
import innovatorsImg from '../images/events/innovators.png'
import lineRoboChallengeImg from '../images/events/line-robo-challenge.png'
import olympiadImg from '../images/events/olympiad.png'
import pitchersImg from '../images/events/pitchers.png'
import quantumHacksImg from '../images/events/quantum-hacks.png'
import questJrImg from '../images/events/quest-jr.png'
import roboFootballImg from '../images/events/robo-football.png'
import speedSprintImg from '../images/events/speed-sprint.png'
import streetImg from '../images/events/street.png'

import byteBrawlDescImg from '../images/events/byte-brawl-desc.png'
import bestManagerDescImg from '../images/events/best-manager-desc.png'
import forumDescImg from '../images/events/forum-desc.png'
import botsRoyaleDescImg from '../images/events/bots-royale-desc.png'
import circuitPremierLeagueDescImg from '../images/events/circuit-premier-league-desc.png'
import quantumHacksDescImg from '../images/events/quantum-hacks-desc.png'

export { bestManagerImg, aquaRushImg, botsRoyaleImg, byteBrawlImg, conclaveImg, droneRaceImg, chaiPeCharchaImg, circuitPremierLeagueImg, cybercodeImg, debateImg, forumImg, goKartRaceImg, innovatorsImg, lineRoboChallengeImg, olympiadImg, pitchersImg, quantumHacksImg, questJrImg, roboFootballImg, speedSprintImg, streetImg, byteBrawlDescImg, bestManagerDescImg, forumDescImg, botsRoyaleDescImg, circuitPremierLeagueDescImg, quantumHacksDescImg }