import { aquaRushDescImg, aquaRushImg, bestManagerDescImg, bestManagerImg, botsRoyaleDescImg, botsRoyaleImg, byteBrawlBgmiImg, byteBrawlCodImg, byteBrawlDescImg, chaiPeCharchaDescImg, chaiPeCharchaImg, circuitPremierLeagueDescImg, circuitPremierLeagueImg, conclaveDescImg, conclaveImg, debateDescImg, debateImg, droneRaceDescImg, droneRaceImg, forumDescImg, forumImg, innovatorsDescImg, innovatorsImg, lineRoboChallengeDescImg, lineRoboChallengeImg, olympiadDescImg, olympiadImg, pitchersDescImg, pitchersImg, quantumHacksDescImg, quantumHacksImg, questJrDescImg, questJrImg, questSrDescImg, questSrImg, roboFootballDescImg, roboFootballImg, speedSprintDescImg, speedSprintImg, streetDescImg, streetImg } from '@/utils/event-images'


export const eventsData = [
    {
        id: "QX_EV_01",
        name: "BEST MANAGER",
        img: bestManagerImg,
        imgDesc: bestManagerDescImg,
        desc: "It is a dynamic arena of unique challenges and tasks where managers can showcase their strategic acumen, decision-making prowess, and innovative leadership skills. This immersive competition will test the mettle of participants, demanding quick thinking, strategic planning, and effective communication.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 400,
        prizePool: 12000,
        location: "Chanakya Seminar Hall, NHCE",
        contact: "Anish B - +91 84318 75412",
        ruleBook: "https://docs.google.com/document/d/1rC7nnaj7M2g0L7LXReRorXwod54rVybcEpA8Pohwtqs/edit?usp=sharing"
    },
    {
        id: "QX_EV_02",
        name: "BYTE BRAWL-BGMI",
        img: byteBrawlBgmiImg,
        imgDesc: byteBrawlDescImg,
        desc: "Immerse yourselves in the world of Battlegrounds Mobile India (BGMI) in a Team DeathMatch to be the final survivor.",
        date: "23/01/24",
        minSize: 4,
        maxSize: 5,
        fixedSize: null,
        fee: 500,
        prizePool: 12000,
        location: "2 ISE classrooms, VMware lab, Eurofins lab",
        contact: "Adnan Azam- +91 99868 67746",
        ruleBook: "https://docs.google.com/document/d/11uOwKVAi4Kzt2KVGcueFqPPuk8YLDWiSCR3lrS2x_d8/edit?usp=sharing"
    },
    {
        id: "QX_EV_03",
        name: "BYTE BRAWL-COD",
        img: byteBrawlCodImg,
        imgDesc: byteBrawlDescImg,
        desc: "Immerse yourselves in the world of Battlegrounds Mobile India (BGMI) in a Team DeathMatch to be the final survivor.",
        date: "25/01/24",
        minSize: 4,
        maxSize: 5,
        fixedSize: null,
        fee: 500,
        prizePool: 12000,
        location: "2 ISE classrooms, VMware lab, Eurofins lab",
        contact: "Adnan Azam- +91 99868 67746",
        ruleBook: "https://docs.google.com/document/d/17y0c8PuY34Dxt5YKjbHmVp278nOz79mEVZq0WcXZPJs/edit?usp=sharing"
    },
    {
        id: "QX_EV_04",
        name: "CREATORS' CONCLAVE",
        img: conclaveImg,
        imgDesc: conclaveDescImg,
        desc: "Participants can immerse themselves in a vibrant convergence of artistic visionaries, technological pioneers, and innovative minds as they gather to share their inspiring stories and unveil groundbreaking creations.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 0,
        prizePool: null,
        location: "Auditorium",
        contact: "Md Aman - 9886959676",
    },
    {
        id: "QX_EV_05",
        name: "CHAI PE CHARCHA",
        img: chaiPeCharchaImg,
        imgDesc: chaiPeCharchaDescImg,
        desc: "Join us for an engaging and thought-provoking discussion featuring renowned experts and thought leaders from the dynamic realm of technology. Delve into the latest trends, emerging challenges, and transformative advancements shaping the technological landscape.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 0,
        prizePool: null,
        location: "Auditorium",
        contact: "Achinth H S - 8904897375",
    },
    {
        id: "QX_EV_06",
        name: "FOUNDERS FORUM",
        img: forumImg,
        imgDesc: forumDescImg,
        desc: "Participants can engage in stimulating discussions trailblazing founders and experienced mentors about disruptive ideas, scalable solutions, and the transformative journey of transforming visions into successful ventures.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 0,
        prizePool: null,
        location: "Auditorium",
        contact: "Keerthana Y - 7975646388",
    },
    {
        id: "QX_EV_07",
        name: "HUSTLER'S STREET",
        img: streetImg,
        imgDesc: streetDescImg,
        desc: "Navigate through a labyrinth of booths showcasing cutting-edge products, services, and solutions from a diverse range of startups. Engage in thought-provoking conversations with passionate founders and industry experts as they delve into the intricacies of their ventures.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 0,
        prizePool: null,
        location: "SVM Hostel Corridor",
        contact: "Gagan M - 8217784192",
    },
    {
        id: "QX_EV_08",
        name: "YOUNG INNOVATORS",
        img: innovatorsImg,
        imgDesc: innovatorsDescImg,
        desc: "Young Innovators is a dynamic showcase of creativity, where brilliant minds converge to present groundbreaking ideas and pioneering projects. From cutting-edge tech solutions to revolutionary concepts, witness the next generation of innovators shaping tomorrow's world.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 2,
        fee: 0,
        prizePool: 6000,
        location: "AIML Corridors",
        contact: "John Joseph R - +91 97405 88099",
        ruleBook: "https://docs.google.com/document/d/1XqqG1Ex8k_ikcDNyV6cAEvyK8ZPpHYS4eVLWyYsgyU0/edit?usp=sharing"
    },
    {
        id: "QX_EV_09",
        name: "OLYMPIAD",
        img: olympiadImg,
        imgDesc: olympiadDescImg,
        desc: "Participants will tackle mind-bending puzzles, solve complex problems, and demonstrate their analytical prowess. The Olympiad promises to be an exhilarating spectacle of academic brilliance and strategic manoeuvring.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 0,
        prizePool: 5000,
        location: "C503,C509",
        contact: "Shreyas P Kuppasad - +91 80957 90154",
        ruleBook: "https://docs.google.com/document/d/1qlBJdU0ivwoLia00LwkNH9C5V21vcxThFZeo9WM0ZaA/edit?usp=sharing"
    },
    {
        id: "QX_EV_10",
        name: "CYBERCODE QUEST JR.",
        img: questJrImg,
        imgDesc: questJrDescImg,
        desc: "Dive into a world of algorithms, data structures, and problem-solving as you tackle a series of challenging coding tasks. Test your skills against fellow students and experience the thrill of competition.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 0,
        prizePool: 5000,
        location: "MCA Labs, Netaji Subhash Chandra Bose Block, NHCE",
        contact: "Abhijit R S - +91 96203 02533",
        ruleBook: "https://docs.google.com/document/d/13bGMzuj9bkcGBjfyEVxpyIfV_HnO0vt62ep8qw5aRpo/edit?usp=sharing"
    },
    {
        id: "QX_EV_11",
        name: "DEBATE",
        img: debateImg,
        imgDesc: debateDescImg,
        desc: "Calling all eloquent and persuasive speakers! Prepare to engage in intellectual discourse and defend your stance.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 2,
        fee: 0,
        prizePool: 5000,
        location: "Tejas Seminar Hall",
        contact: "Adrian Mathew - +91 91080 37471",
        ruleBook: "https://docs.google.com/document/d/1Ij-oEuThzrFUa3Dk4DsycdFCXsKhR38GIPfnjeLUGH4/edit?usp=sharing"
    },
    {
        id: "QX_EV_12",
        name: "QUANTUM HACKS",
        img: quantumHacksImg,
        imgDesc: quantumHacksDescImg,
        desc: "This is a dynamic arena where collaboration and ingenuity converge to tackle real-world challenges. This immersive event extends beyond mere competition; it's a journey of learning, growth, and the collective pursuit of meaningful impact.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 3,
        fee: 1000,
        prizePool: 60000,
        location: "Library, Amar Jawan Block, NHCE",
        contact: "Shazib Wani - +91 60058 33691",
        ruleBook: "https://docs.google.com/document/d/1Sj1LtHyfWayr4HiBfGvGGyk9ws12msW2bcFpg7ameKU/edit?usp=sharing"
    },
    {
        id: "QX_EV_13",
        name: "CYBERCODE QUEST SR.",
        img: questSrImg,
        imgDesc: questSrDescImg,
        desc: "This challenge is designed to test the participants' analytical skills and push them to the boundaries of their algorithmic knowledge. They will be confronted with complex problems and must devise innovative solutions.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 200,
        prizePool: 15000,
        location: "MCA labs",
        contact: "Abhijit R S - +91 96203 02533",
        ruleBook: "https://docs.google.com/document/d/1J5DGivvh_lm1pX279UptDjJHbjD7sdlv-5Z0aZ6KYyY/edit?usp=sharing"
    },
    {
        id: "QX_EV_14",
        name: "CIRCUIT PREMIER LEAGUE",
        img: circuitPremierLeagueImg,
        imgDesc: circuitPremierLeagueDescImg,
        desc: "Delve into the intricate world of embedded systems, assembly language, and hardware mastery. From unravelling coding enigmas to crafting ingenious circuits, participants will be immersed in a day of dynamic challenges and inventive exploration.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 3,
        fee: 500,
        prizePool: 20000,
        location: "ECE Labs, Netaji Subhash Chandra Bose Block, NHCE",
        contact: "Rohanth Hari - +91 91104 18016",
        ruleBook: "https://docs.google.com/document/d/1ii7UAxHL5mSlc59EP201FLaeob1PEwC6opXtn-GkDg4/edit?usp=sharing"
    },
    {
        id: "QX_EV_15",
        name: "PITCHERS",
        img: pitchersImg,
        imgDesc: pitchersDescImg,
        desc: "This dynamic platform offers the chance to pitch innovative concepts to a panel of seasoned judges and secure potential investments. Witness the thrill of investment negotiations, creative pitches, and the birth of future enterprises.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 3,
        fee: 1000,
        prizePool: 20000,
        location: "Tejas Seminar Hall",
        contact: "Shashank S - +91 91081 31629",
        ruleBook: "https://docs.google.com/document/d/1y3g807xy9ptZVoNIkS21vffYxobAuIFWUWQS0k9tgDg/edit?usp=sharing"
    },
    {
        id: "QX_EV_16",
        name: "SPEED SPRINT",
        img: speedSprintImg,
        imgDesc: speedSprintDescImg,
        desc: "Adrenaline-fueled drivers will showcase their mastery of control and manoeuvrability amidst challenging courses and exhilarating speeds.",
        date: "23/01/2024",
        minSize: null,
        maxSize: null,
        fixedSize: 3,
        fee: 300,
        prizePool: 15000,
        location: "Ground, NHCE",
        contact: "Syed Hannan - +91 80954 18861",
        ruleBook: "https://docs.google.com/document/d/1bGla0epgaH-7F0OG-4VZE2fg-0g6DXl3UWN3D9ASzEc/edit?usp=sharing"
    },
    {
        id: "QX_EV_17",
        name: "AQUA RUSH",
        img: aquaRushImg,
        imgDesc: aquaRushDescImg,
        desc: "Prepare to be captivated by the thrilling spectacle of the RC Boat Race, where miniature speedsters navigate the aquatic arena with precision and agility.",
        date: "24/01/24", 
        minSize: null,
        maxSize: null,
        fixedSize: 2,
        fee: 300,
        prizePool: 15000,
        location: "Sports Ground, NHCE.",
        contact: "Diya Chandrashekar - +91 79755 74212",
        ruleBook: "https://docs.google.com/document/d/1GsYbnEIberwL0MyMJJ65uiYS7FHYIR5LYgEUPlVszmo/edit"
    },
    {
        id: "QX_EV_18",
        name: "BOTS ROYALE",
        img: botsRoyaleImg,
        imgDesc: botsRoyaleDescImg,
        desc: "It is a combat robotics competition in which teams design, build, and operate remote-controlled robots to fight in an arena combat elimination tournament. The robots are armed with a variety of weapons, such as hammers, saws, and blades, and the goal is to disable or destroy the opponent's robot.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 5,
        fee: 1000,
        prizePool: 130000,
        location: "Basketball Quadrangle, NHCE",
        contact: "Yashasvi Linga Reddy - +91 63648 83602",
        ruleBook: "https://docs.google.com/document/d/1455mmKqWtwvj4YsubozNAVzhFD8vho0eTkbDA01C2sI/edit"
    },
    {
        id: "QX_EV_19",
        name: "ROBO FOOTBALL",
        img: roboFootballImg,
        imgDesc: roboFootballDescImg,
        desc: "Robo Soccer is a captivating competition where teams of autonomous robots engage in a thrilling game of football. This event showcases the culmination of cutting-edge robotics technology, strategic programming, and teamwork, immersing spectators in a world where technology meets sport.",
        date: "24/01/2024",
        minSize: null,
        maxSize: null,
        fixedSize: 2,
        fee: 300,
        prizePool: 15000,
        location: "Basketball Quadrangle, NHCE",
        contact: "M Chandana - +91 63640 45698",
        ruleBook: "https://docs.google.com/document/d/1gTC9i9SMPDdXQtXTsZv29fJjyw6JmN8oYt97XCoupCI/edit?usp=sharing"
    },
    {
        id: "QX_EV_20",
        name: "LINE ROBOT CHALLENGE",
        img: lineRoboChallengeImg,
        imgDesc: lineRoboChallengeDescImg,
        desc: "Prepare to test your skills and unleash your creativity at the Line robot Challenge where you'll design, build, and program autonomous robots to navigate a challenging line course.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 2,
        fee: 300,
        prizePool: 10000,
        location: "Ground Floor, Netaji Subhash Chandra Bose Block, NHCE",
        contact: "G Guru Saran Reddy - +91 82474 23833",
        ruleBook: "https://docs.google.com/document/d/1afostJonJ1YyM0ku6X7YSOrJ8x53DCCZf-8ewl04E_M/edit?usp=sharing"
    },
    {
        id: "QX_EV_21",
        name: "DRONE RACE",
        img: droneRaceImg,
        imgDesc: droneRaceDescImg,
        desc: "Witness the ultimate drone racing competition, where pilots will demonstrate their mastery of control and manoeuvrability amidst challenging courses and breathtaking aerial manoeuvres.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        prizePool: 45000,
        location: "Sports Ground, NHCE",
        contact: "Harshavardhan PR - +91 86189 86078",
        ruleBook: "https://docs.google.com/document/d/1RmiPcnPU_dsr2SLDctIgNqgWtaZpEqivRvZevm0blu4/edit?usp=sharing"
    },  
]