import bestManagerImg from '../images/events/best-manager.png'
import aquaRushImg from '../images/events/aqua-rush.png'
import botsRoyaleImg from '../images/events/bots-royale.png'
import byteBrawlCodImg from '../images/events/byte-brawl-cod.png'
import byteBrawlBgmiImg from '../images/events/byte-brawl-bgmi.png'
import conclaveImg from '../images/events/conclave.png'
import droneRaceImg from '../images/events/drone-race.png'
import chaiPeCharchaImg from '../images/events/chai-pe-charcha.png'
import circuitPremierLeagueImg from '../images/events/circuit-premier-league.png'
import questSrImg from '../images/events/quest-sr.png'
import debateImg from '../images/events/debate.png'
import forumImg from '../images/events/forum.png'
import innovatorsImg from '../images/events/innovators.png'
import lineRoboChallengeImg from '../images/events/line-robo-challenge.png'
import olympiadImg from '../images/events/olympiad.png'
import pitchersImg from '../images/events/pitchers.png'
import quantumHacksImg from '../images/events/quantum-hacks.png'
import questJrImg from '../images/events/quest-jr.png'
import roboFootballImg from '../images/events/robo-football.png'
import speedSprintImg from '../images/events/speed-sprint.png'
import streetImg from '../images/events/street.png'

import bestManagerDescImg from '../images/events/best-manager-desc.png'
import aquaRushDescImg from '../images/events/aqua-rush-desc.png'
import botsRoyaleDescImg from '../images/events/bots-royale-desc.png'
import byteBrawlCodDescImg from '../images/events/byte-brawl-cod-desc.png'
import byteBrawlBgmiDescImg from '../images/events/byte-brawl-bgmi-desc.png'
import conclaveDescImg from '../images/events/conclave-desc.png'
import droneRaceDescImg from '../images/events/drone-race-desc.png'
import chaiPeCharchaDescImg from '../images/events/chai-pe-charcha-desc.png'
import circuitPremierLeagueDescImg from '../images/events/circuit-premier-league-desc.png'
import questSrDescImg from '../images/events/quest-sr-desc.png'
import debateDescImg from '../images/events/debate-desc.png'
import forumDescImg from '../images/events/forum-desc.png'
import innovatorsDescImg from '../images/events/innovators-desc.png'
import lineRoboChallengeDescImg from '../images/events/line-robo-challenge-desc.png'
import olympiadDescImg from '../images/events/olympiad-desc.png'
import pitchersDescImg from '../images/events/pitchers-desc.png'
import quantumHacksDescImg from '../images/events/quantum-hacks-desc.png'
import questJrDescImg from '../images/events/quest-jr-desc.png'
import roboFootballDescImg from '../images/events/robo-football-desc.png'
import speedSprintDescImg from '../images/events/speed-sprint-desc.png'
import streetDescImg from '../images/events/street-desc.png'


export { bestManagerImg, aquaRushImg, botsRoyaleImg, byteBrawlCodImg, byteBrawlBgmiImg, conclaveImg, droneRaceImg, chaiPeCharchaImg, circuitPremierLeagueImg, questSrImg, questSrDescImg, debateImg, forumImg, innovatorsImg, lineRoboChallengeImg, olympiadImg, pitchersImg, quantumHacksImg, questJrImg, roboFootballImg, speedSprintImg, streetImg, byteBrawlCodDescImg, byteBrawlBgmiDescImg, bestManagerDescImg, forumDescImg, botsRoyaleDescImg, circuitPremierLeagueDescImg, quantumHacksDescImg, aquaRushDescImg, conclaveDescImg, droneRaceDescImg, chaiPeCharchaDescImg, debateDescImg, innovatorsDescImg, olympiadDescImg, pitchersDescImg, lineRoboChallengeDescImg, questJrDescImg, roboFootballDescImg, speedSprintDescImg, streetDescImg }