import { androidDevelopmentDescImg, androidDevelopmentImg, artificialIntelligenceDescImg, artificialIntelligenceImg, cryptocurrencyDescImg, cryptocurrencyImg, dataAnalyticsUsingRDescImg, dataAnalyticsUsingRImg, deepLearningDescImg, deepLearningImg, designThinkingDescImg, designThinkingImg, digitalMarketingDescImg, digitalMarketingImg, ethicalHackingDescImg, ethicalHackingImg, gameDevelopmentDescImg, gameDevelopmentImg, googleCloudComputingDescImg, googleCloudComputingImg, gsmGpsTrackingSystemDescImg, gsmGpsTrackingSystemImg, homeAutomationDescImg, homeAutomationImg, machineLearningDescImg, machineLearningImg, nftDescImg, nftImg, nodejsDescImg, nodejsImg, openSourceWorkflowDescImg, openSourceWorkflowImg, opencvControlOfPointerDescImg, opencvControlOfPointerImg, opencvImageCaptureDescImg, opencvImageCaptureImg, opencvPhotoCaptureDescImg, opencvPhotoCaptureImg, phpDescImg, phpImg, reactjsDescImg, reactjsImg, sixthSenseDescImg, sixthSenseImg, smartBuildingSystemDescImg, smartBuildingSystemImg, swarmRoboticsDescImg, swarmRoboticsImg, web3DescImg, web3Img, wifiRoboticsDescImg, wifiRoboticsImg } from "./workshop-images";


export const workshopsdata = [
    {
        id: "QX_WS_01",
        name: "Android App Development",
        img: androidDevelopmentImg,
        imgDesc: androidDevelopmentDescImg,
        desc: "Gain the skills to create innovative and engaging Android apps that reach a global audience",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_02",
        name: "Open Source",
        img: openSourceWorkflowImg,
        imgDesc: openSourceWorkflowDescImg,
        desc: " Master the fundamentals of open-source software and become a contributor.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_03",
        name: "Computer Vision-Based Image Capture",
        img: opencvImageCaptureImg,
        imgDesc: opencvImageCaptureDescImg,
        desc: "Learn about the intricacies of performing actions resulting from computer vision-based image capture.",
        date: "",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: "",
        location: "",
    },
    {
        id: "QX_WS_04",
        name: "GPS/GSM based Defense Tracking System",
        img: gsmGpsTrackingSystemImg,
        imgDesc: gsmGpsTrackingSystemDescImg,
        desc: "Track the exact location of any device using GSM/GPS modules.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_05",
        name: "Home Automation",
        img: homeAutomationImg,
        imgDesc: homeAutomationDescImg,
        desc: " Automate your home using smart devices and programming",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_06",
        name: "Sixth Sense Robotics",
        img: sixthSenseImg,
        imgDesc: sixthSenseDescImg,
        desc: "Create robots that can interact with the physical world.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_07",
        name: "Smart Building System",
        img: smartBuildingSystemImg,
        imgDesc: smartBuildingSystemDescImg,
        desc: "Learn about IoT-based smart building systems using various sensors.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_08",
        name: "Swarm Robotics",
        img: swarmRoboticsImg,
        imgDesc: swarmRoboticsDescImg,
        desc: "Build swarms of robots to perform complex tasks autonomously.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_09",
        name: "Wifi Robotics",
        img: wifiRoboticsImg,
        imgDesc: wifiRoboticsDescImg,
        desc: "Create robots that can be operated remotely via Wi-Fi.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_10",
        name: "Node.js",
        img: nodejsImg,
        imgDesc: nodejsDescImg,
        desc: "Discover how to build scalable and performant backend servers with Node.js",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_11",
        name: "",
        img: phpImg,
        imgDesc: phpDescImg,
        desc: "Learn to build web applications that can grow and adapt to changing needs.",
        date: "",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: "",
        location: "",
    },
    {
        id: "QX_WS_12",
        name: "CryptoCurrency/Blockchain",
        img: cryptocurrencyImg,
        imgDesc: cryptocurrencyDescImg,
        desc: "Learn about blockchain, types of cryptocurrency, trading and developing your own crypto trading strategies.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_13",
        name: "NFT",
        img: nftImg,
        imgDesc: nftDescImg,
        desc: "Build a NFT marketplace using Python to buy and sell NFTs.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_14",
        name: "Computer Vision based Control of Pointer",
        img: opencvControlOfPointerImg,
        imgDesc: opencvControlOfPointerDescImg,
        desc: " Develop a controller to control the cursor using hand gestures.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_15",
        name: "Computer Vision based Smart Photo Capture",
        img: opencvPhotoCaptureImg,
        imgDesc: opencvPhotoCaptureDescImg,
        desc: "Develop an app that can automatically photograph documents.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_16",
        name: "React.js",
        img: reactjsImg,
        imgDesc: reactjsDescImg,
        desc: "Master the leading JavaScript library for building user interfaces.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_17",
        name: "Data Analytics using R",
        img: dataAnalyticsUsingRImg,
        imgDesc: dataAnalyticsUsingRDescImg,
        desc: "Master data exploration and analysis using R.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 600,
        location: "",
    },
    {
        id: "QX_WS_18",
        name: "Deep Learning",
        img: deepLearningImg,
        imgDesc: deepLearningDescImg,
        desc: "Discover how to build and train your own deep learning models",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_19",
        name: "Design Thinking - UI/UX",
        img: designThinkingImg,
        imgDesc: designThinkingDescImg,
        desc: "Master the fundamentals of UI/UX and redesign your favorite app.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_20",
        name: "Digital Marketing",
        img: digitalMarketingImg,
        imgDesc: digitalMarketingDescImg,
        desc: "unlock the potential of marketing strategies used in various channels.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_21",
        name: "Game Development",
        img: gameDevelopmentImg,
        imgDesc: gameDevelopmentDescImg,
        desc: "Create immersive and engaging games using technical expertise.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_22",
        name: "",
        img: googleCloudComputingImg,
        imgDesc: googleCloudComputingDescImg,
        desc: "Learn to build and deploy ML models on Google Cloud Platform.",
        date: "",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: "",
        location: "",
    },
    {
        id: "QX_WS_23",
        name: "Web 3.0",
        img: web3Img,
        imgDesc: web3DescImg,
        desc: "Master the technology that will power the next generation of the internet.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_24",
        name: "Artificial Intelligence",
        img: artificialIntelligenceImg,
        imgDesc: artificialIntelligenceDescImg,
        desc: "Learn about the various branches of AI and develop your own virtual assistant.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_25",
        name: "Ethical Hacking",
        img: ethicalHackingImg,
        imgDesc: ethicalHackingDescImg,
        desc: "Master how to exploit vulnerabilities and gain access to web apps.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_26",
        name: "Machine Learning",
        img: machineLearningImg,
        imgDesc: machineLearningDescImg,
        desc: "Master the fundamentals of ML and build predictive models",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    }
]


/**
 * 
 * ,
    {
        id: "QX_WS_27",
        name: "Data Science",
        img: "",
        imgDesc: "",
        desc: "Learn to extract insights from data to solve real-world problems",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },

    {
        id: "QX_WS_28",
        name: "Humanoid Robotics",
        img: "",
        imgDesc: "",
        desc: "Build robots that can emulate human form and function.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_29",
        name: "Guided Robotics",
        img: "",
        imgDesc: "",
        desc: "Build a sensor-driven machine that reacts to its surroundings.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_30",
        name: "Gesture robotics",
        img: "",
        imgDesc: "",
        desc: "Discover the unstoppable rise of robotics and automation.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_31",
        name: "DSA",
        img: "",
        imgDesc: "",
        desc: "",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_32",
        name: "AWS",
        img: "",
        imgDesc: "",
        desc: "",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_33",
        name: "DevOps",
        img: "",
        imgDesc: "",
        desc: "",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 600,
        location: "",
    },
    {
        id: "QX_WS_34",
        name: "Computer Vision based Tracking System",
        img: "",
        imgDesc: "",
        desc: "",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
 * 
 */