import { androidDevelopmentDescImg, androidDevelopmentImg, artificialIntelligenceDescImg, artificialIntelligenceImg, awsDescImg, awsImg, cvTrackingSystemDescImg, cvTrackingSystemImg, dataScienceDescImg, dataScienceImg, databasesDescImg, databasesImg, deepLearningDescImg, deepLearningImg, designThinkingDescImg, designThinkingImg, devopsDescImg, devopsImg, digitalMarketingDescImg, digitalMarketingImg, dsaImg, ethicalHackingDescImg, ethicalHackingImg, gameDevelopmentDescImg, gameDevelopmentImg, gestureRoboticsDescImg, gestureRoboticsImg, gsmGpsTrackingSystemDescImg, gsmGpsTrackingSystemImg, guidedRoboticsDescImg, guidedRoboticsImg, homeAutomationDescImg, homeAutomationImg, humanoidRoboticsDescImg, humanoidRoboticsImg, machineLearningDescImg, machineLearningImg, nftDescImg, nftImg, nodejsDescImg, nodejsImg, openSourceWorkflowDescImg, openSourceWorkflowImg, opencvControlOfPointerDescImg, opencvControlOfPointerImg, opencvPhotoCaptureDescImg, opencvPhotoCaptureImg, reactjsDescImg, reactjsImg, sixthSenseDescImg, sixthSenseImg, smartBuildingSystemDescImg, smartBuildingSystemImg, swarmRoboticsDescImg, swarmRoboticsImg, web3DescImg, web3Img, wifiRoboticsDescImg, wifiRoboticsImg } from "./workshop-images";


export const hardwareWorkshopsData = [
    {
        id: "QX_WS_01",
        name: "Swarm Robotics",
        img: swarmRoboticsImg,
        imgDesc: swarmRoboticsDescImg,
        desc: "Develop autonomous swarm robots with master-slave communication, integrating sensors, wireless communication, and Arduino programming for a practical experience in DC motors, RF modules, and microcontrollers.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_02",
        name: "WiFi Robotics",
        img: wifiRoboticsImg,
        imgDesc: wifiRoboticsDescImg,
        desc: "Build a WiFi-controlled robot using ESP8266, gaining hands-on experience in Arduino programming, wireless networking, and designing a web-based interface for remote operation.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_03",
        name: "Gesture Robotics",
        img: gestureRoboticsImg,
        imgDesc: gestureRoboticsDescImg,
        desc: "Learn to design, develop, and test gesture-based robots with accelerometers, providing insights into human-machine interaction technologies and practical experience with DC motors, microcontrollers, and sensors.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_04",
        name: "Guided Robotics",
        img: guidedRoboticsImg,
        imgDesc: guidedRoboticsDescImg,
        desc: "Explore autonomous line follower robots using Arduino Uno, IR sensors, and C++ programming, gaining knowledge in sensor-guided autonomous robotics for various applications.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_05",
        name: "Sixth Sense",
        img: sixthSenseImg,
        imgDesc: sixthSenseDescImg,
        desc: "Gain understanding and practical skills in Sixth Sense technology, image processing using OpenCV in Python, Arduino architecture, and programming to develop and test a robot controlled by natural hand gestures.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_06",
        name: "Home Automation",
        img: homeAutomationImg,
        imgDesc: homeAutomationDescImg,
        desc: "Develop an IoT-based home automation system using Bluetooth technology, Arduino Uno, and relay switches, enabling remote control of electrical devices with a smartphone and learning IoT basics.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_07",
        name: "Smart Building System",
        img: smartBuildingSystemImg,
        imgDesc: smartBuildingSystemDescImg,
        desc: "Build an IoT-based smart lights system using PIR sensors, Arduino programming, and cloud connectivity, allowing analysis of occupancy patterns and power consumption in a meeting room.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_08",
        name: "Computer Vision Based Tracking System",
        img: cvTrackingSystemImg,
        imgDesc: cvTrackingSystemDescImg,
        desc: "Develop a hands-on computer vision-based mouse using Python, exploring image processing algorithms like thresholding, canny edge detection, and object tracking for cursor control.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_09",
        name: "Humanoid Robotics",
        img: humanoidRoboticsImg,
        imgDesc: humanoidRoboticsDescImg,
        desc: "Build a biped walking robot with six degrees of freedom, understanding servo motors, embedded systems, microcontrollers, and programming logic behind human walking actions using Arduino.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_10",
        name: "GPS/GSM Based Defence Tracking System",
        img: gsmGpsTrackingSystemImg,
        imgDesc: gsmGpsTrackingSystemDescImg,
        desc: "Construct a GPS and GSM-based tracker with Arduino, gaining practical knowledge in GPS modules, antennas, GSM modules, and implementing Arduino programming for real-time position updates on Google Maps.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    }
]

export const softwareWorkshopsData = [
    {
        id: "QX_WS_11",
        name: "Machine Learning",
        img: machineLearningImg,
        imgDesc: machineLearningDescImg,
        desc: "This comprehensive workshop will equip you with the fundamental concepts, practical skills, and hands-on experience to master machine learning techniques.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_12",
        name: "Deep Learning",
        img: deepLearningImg,
        imgDesc: deepLearningDescImg,
        desc: "Create a deep learning model for image classification using Convolutional Neural Networks, covering data collection, CNN architecture selection, model training, evaluation, and deployment to categorise images into distinct classes.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_13",
        name: "Artificial Intelligence",
        img: artificialIntelligenceImg,
        imgDesc: artificialIntelligenceDescImg,
        desc: "Build an intelligent virtual assistant capable of answering questions and performing tasks, incorporating natural language processing, computer vision, and robotics, with an emphasis on designing, implementing, evaluating, and deploying the virtual assistant.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_14",
        name: "Ethical Hacking",
        img: ethicalHackingImg,
        imgDesc: ethicalHackingDescImg,
        desc: "Conduct a web application penetration test, encompassing reconnaissance, scanning, vulnerability assessment, penetration testing, and reporting to identify and address security vulnerabilities in a target web application.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_15",
        name: "Data Science",
        img: dataScienceImg,
        imgDesc: dataScienceDescImg,
        desc: "Explore the art of extracting meaningful insights from data, master fundamental analysis techniques, and gain hands-on experience with industry-standard tools.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_16",
        name: "Introduction to Databases",
        img: databasesImg,
        imgDesc: databasesDescImg,
        desc: "This workshop ensures participants gain a strong grasp of database fundamentals, proficiency in SQL usage, and insights into deciding between relational and non-relational databases. Whether you're new to databases or seeking a knowledge refresher, the session empowers you to master organised and efficient data management.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_17",
        name: "DSA",
        img: dsaImg,
        imgDesc: guidedRoboticsDescImg,
        desc: "This intensive workshop delves into the core concepts of Data Structures and Algorithms (DSA), equipping you with the knowledge and practical skills to become a proficient and efficient programmer.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_18",
        name: "Design Thinking UI/UX",
        img: designThinkingImg,
        imgDesc: designThinkingDescImg,
        desc: "Redesign a popular app using the design thinking process, involving user research, problem definition, ideation, prototyping, user testing, and refining designs to enhance the app's user experience.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_19",
        name: "Digital Marketing",
        img: digitalMarketingImg,
        imgDesc: digitalMarketingDescImg,
        desc: "Collaborate to create a comprehensive digital marketing plan for a small business, covering SEO, PPC, social media, content marketing, email marketing, affiliate marketing, influencer marketing, CRO, and web analytics.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_20",
        name: "Game Development",
        img: gameDevelopmentImg,
        imgDesc: gameDevelopmentDescImg,
        desc: "Design and prototype an interactive game using game design principles, including elements, mechanics, story, levels, UI/UX, testing, and balancing to create an engaging and enjoyable gaming experience.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_21",
        name: "Web 3.0",
        img: web3Img,
        imgDesc: web3DescImg,
        desc: "Introduce participants to Web3 development by building a decentralised exchange (DEX) from scratch, covering smart contracts, blockchain wallets, web3 APIs, and allowing cryptocurrency trading without central intermediaries.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_22",
        name: "NFT",
        img: nftImg,
        imgDesc: nftDescImg,
        desc: "Build an NFT marketplace using Python, covering NFT standards, minting, trading, Python libraries for NFTs, and testing the complete system for minting, buying, and selling NFTs.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_23",
        name: "Computer Vision Smart Photo Capture",
        img: opencvPhotoCaptureImg,
        imgDesc: opencvPhotoCaptureDescImg,
        desc: "Develop a smart photo capture app using computer vision to automatically photograph documents, incorporating object detection, image alignment, and evaluation for accuracy and reliability.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_24",
        name: "Computer Vision Based Control of Pointer",
        img: opencvControlOfPointerImg,
        imgDesc: opencvControlOfPointerDescImg,
        desc: "Build a computer vision-based pointer controller that uses hand gestures to control the mouse cursor, covering development platforms, hand detection, object detection, and evaluating accuracy for intuitive control.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_25",
        name: "React.js",
        img: reactjsImg,
        imgDesc: reactjsDescImg,
        desc: "Create a to-do list web app using React.js, covering component creation, state management, event handling, conditional rendering, and styling for a user-friendly and functional application.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_26",
        name: "Android App Development",
        img: androidDevelopmentImg,
        imgDesc: androidDevelopmentDescImg,
        desc: "Develop a to-do list mobile app using Flutter, covering widget and layout design, state management, networking, testing, and deployment for a cross-platform Android app.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_27",
        name: "Node.js",
        img: nodejsImg,
        imgDesc: nodejsDescImg,
        desc: "Develop a simple blog API using Node.js and Express.js, covering MongoDB integration, REST API design, error handling, authentication, and deployment to enable CRUD operations for blog posts.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_28",
        name: "Open Source Workflow",
        img: openSourceWorkflowImg,
        imgDesc: openSourceWorkflowDescImg,
        desc: "Choose and contribute to an open source project, involving selecting a project, making a meaningful contribution, and receiving feedback on the contribution to participate in the open source community actively.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_29",
        name: "DevOps",
        img: devopsImg,
        imgDesc: devopsDescImg,
        desc: "Gain the skills and knowledge needed to implement DevOps practices effectively within your organisation, fostering a culture of continuous improvement and collaboration for enhanced software delivery.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 600,
        location: "",
    },
    {
        id: "QX_WS_30",
        name: "AWS",
        img: awsImg,
        imgDesc: awsDescImg,
        desc: "Unlock the full potential of Amazon Web Services (AWS) with our immersive workshop designed for cloud enthusiasts and professionals. In this comprehensive training, participants will delve into the core AWS services.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 600,
        location: "",
    }
]

export const workshopsData = [
    {
        id: "QX_WS_01",
        name: "Swarm Robotics",
        img: swarmRoboticsImg,
        imgDesc: swarmRoboticsDescImg,
        desc: "Develop autonomous swarm robots with master-slave communication, integrating sensors, wireless communication, and Arduino programming for a practical experience in DC motors, RF modules, and microcontrollers.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_02",
        name: "WiFi Robotics",
        img: wifiRoboticsImg,
        imgDesc: wifiRoboticsDescImg,
        desc: "Build a WiFi-controlled robot using ESP8266, gaining hands-on experience in Arduino programming, wireless networking, and designing a web-based interface for remote operation.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_03",
        name: "Gesture Robotics",
        img: gestureRoboticsImg,
        imgDesc: gestureRoboticsDescImg,
        desc: "Learn to design, develop, and test gesture-based robots with accelerometers, providing insights into human-machine interaction technologies and practical experience with DC motors, microcontrollers, and sensors.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_04",
        name: "Guided Robotics",
        img: guidedRoboticsImg,
        imgDesc: guidedRoboticsDescImg,
        desc: "Explore autonomous line follower robots using Arduino Uno, IR sensors, and C++ programming, gaining knowledge in sensor-guided autonomous robotics for various applications.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_05",
        name: "Sixth Sense",
        img: sixthSenseImg,
        imgDesc: sixthSenseDescImg,
        desc: "Gain understanding and practical skills in Sixth Sense technology, image processing using OpenCV in Python, Arduino architecture, and programming to develop and test a robot controlled by natural hand gestures.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_06",
        name: "Home Automation",
        img: homeAutomationImg,
        imgDesc: homeAutomationDescImg,
        desc: "Develop an IoT-based home automation system using Bluetooth technology, Arduino Uno, and relay switches, enabling remote control of electrical devices with a smartphone and learning IoT basics.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_07",
        name: "Smart Building System",
        img: smartBuildingSystemImg,
        imgDesc: smartBuildingSystemDescImg,
        desc: "Build an IoT-based smart lights system using PIR sensors, Arduino programming, and cloud connectivity, allowing analysis of occupancy patterns and power consumption in a meeting room.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_08",
        name: "Computer Vision Based Tracking System",
        img: cvTrackingSystemImg,
        imgDesc: cvTrackingSystemDescImg,
        desc: "Develop a hands-on computer vision-based mouse using Python, exploring image processing algorithms like thresholding, canny edge detection, and object tracking for cursor control.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_09",
        name: "Humanoid Robotics",
        img: humanoidRoboticsImg,
        imgDesc: humanoidRoboticsDescImg,
        desc: "Build a biped walking robot with six degrees of freedom, understanding servo motors, embedded systems, microcontrollers, and programming logic behind human walking actions using Arduino.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_10",
        name: "GPS/GSM Based Defence Tracking System",
        img: gsmGpsTrackingSystemImg,
        imgDesc: gsmGpsTrackingSystemDescImg,
        desc: "Construct a GPS and GSM-based tracker with Arduino, gaining practical knowledge in GPS modules, antennas, GSM modules, and implementing Arduino programming for real-time position updates on Google Maps.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 1000,
        location: "",
    },
    {
        id: "QX_WS_11",
        name: "Machine Learning",
        img: machineLearningImg,
        imgDesc: machineLearningDescImg,
        desc: "This comprehensive workshop will equip you with the fundamental concepts, practical skills, and hands-on experience to master machine learning techniques.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_12",
        name: "Deep Learning",
        img: deepLearningImg,
        imgDesc: deepLearningDescImg,
        desc: "Create a deep learning model for image classification using Convolutional Neural Networks, covering data collection, CNN architecture selection, model training, evaluation, and deployment to categorise images into distinct classes.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_13",
        name: "Artificial Intelligence",
        img: artificialIntelligenceImg,
        imgDesc: artificialIntelligenceDescImg,
        desc: "Build an intelligent virtual assistant capable of answering questions and performing tasks, incorporating natural language processing, computer vision, and robotics, with an emphasis on designing, implementing, evaluating, and deploying the virtual assistant.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_14",
        name: "Ethical Hacking",
        img: ethicalHackingImg,
        imgDesc: ethicalHackingDescImg,
        desc: "Conduct a web application penetration test, encompassing reconnaissance, scanning, vulnerability assessment, penetration testing, and reporting to identify and address security vulnerabilities in a target web application.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_15",
        name: "Data Science",
        img: dataScienceImg,
        imgDesc: dataScienceDescImg,
        desc: "Explore the art of extracting meaningful insights from data, master fundamental analysis techniques, and gain hands-on experience with industry-standard tools.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_16",
        name: "Introduction to Databases",
        img: databasesImg,
        imgDesc: databasesDescImg,
        desc: "This workshop ensures participants gain a strong grasp of database fundamentals, proficiency in SQL usage, and insights into deciding between relational and non-relational databases. Whether you're new to databases or seeking a knowledge refresher, the session empowers you to master organised and efficient data management.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_17",
        name: "DSA",
        img: dsaImg,
        imgDesc: guidedRoboticsDescImg,
        desc: "This intensive workshop delves into the core concepts of Data Structures and Algorithms (DSA), equipping you with the knowledge and practical skills to become a proficient and efficient programmer.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_18",
        name: "Design Thinking UI/UX",
        img: designThinkingImg,
        imgDesc: designThinkingDescImg,
        desc: "Redesign a popular app using the design thinking process, involving user research, problem definition, ideation, prototyping, user testing, and refining designs to enhance the app's user experience.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_19",
        name: "Digital Marketing",
        img: digitalMarketingImg,
        imgDesc: digitalMarketingDescImg,
        desc: "Collaborate to create a comprehensive digital marketing plan for a small business, covering SEO, PPC, social media, content marketing, email marketing, affiliate marketing, influencer marketing, CRO, and web analytics.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_20",
        name: "Game Development",
        img: gameDevelopmentImg,
        imgDesc: gameDevelopmentDescImg,
        desc: "Design and prototype an interactive game using game design principles, including elements, mechanics, story, levels, UI/UX, testing, and balancing to create an engaging and enjoyable gaming experience.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_21",
        name: "Web 3.0",
        img: web3Img,
        imgDesc: web3DescImg,
        desc: "Introduce participants to Web3 development by building a decentralised exchange (DEX) from scratch, covering smart contracts, blockchain wallets, web3 APIs, and allowing cryptocurrency trading without central intermediaries.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_22",
        name: "NFT",
        img: nftImg,
        imgDesc: nftDescImg,
        desc: "Build an NFT marketplace using Python, covering NFT standards, minting, trading, Python libraries for NFTs, and testing the complete system for minting, buying, and selling NFTs.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_23",
        name: "Computer Vision Smart Photo Capture",
        img: opencvPhotoCaptureImg,
        imgDesc: opencvPhotoCaptureDescImg,
        desc: "Develop a smart photo capture app using computer vision to automatically photograph documents, incorporating object detection, image alignment, and evaluation for accuracy and reliability.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_24",
        name: "Computer Vision Based Control of Pointer",
        img: opencvControlOfPointerImg,
        imgDesc: opencvControlOfPointerDescImg,
        desc: "Build a computer vision-based pointer controller that uses hand gestures to control the mouse cursor, covering development platforms, hand detection, object detection, and evaluating accuracy for intuitive control.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_25",
        name: "React.js",
        img: reactjsImg,
        imgDesc: reactjsDescImg,
        desc: "Create a to-do list web app using React.js, covering component creation, state management, event handling, conditional rendering, and styling for a user-friendly and functional application.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_26",
        name: "Android App Development",
        img: androidDevelopmentImg,
        imgDesc: androidDevelopmentDescImg,
        desc: "Develop a to-do list mobile app using Flutter, covering widget and layout design, state management, networking, testing, and deployment for a cross-platform Android app.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_27",
        name: "Node.js",
        img: nodejsImg,
        imgDesc: nodejsDescImg,
        desc: "Develop a simple blog API using Node.js and Express.js, covering MongoDB integration, REST API design, error handling, authentication, and deployment to enable CRUD operations for blog posts.",
        date: "25/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_28",
        name: "Open Source Workflow",
        img: openSourceWorkflowImg,
        imgDesc: openSourceWorkflowDescImg,
        desc: "Choose and contribute to an open source project, involving selecting a project, making a meaningful contribution, and receiving feedback on the contribution to participate in the open source community actively.",
        date: "23/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 500,
        location: "",
    },
    {
        id: "QX_WS_29",
        name: "DevOps",
        img: devopsImg,
        imgDesc: devopsDescImg,
        desc: "Gain the skills and knowledge needed to implement DevOps practices effectively within your organisation, fostering a culture of continuous improvement and collaboration for enhanced software delivery.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 600,
        location: "",
    },
    {
        id: "QX_WS_30",
        name: "AWS",
        img: awsImg,
        imgDesc: awsDescImg,
        desc: "Unlock the full potential of Amazon Web Services (AWS) with our immersive workshop designed for cloud enthusiasts and professionals. In this comprehensive training, participants will delve into the core AWS services.",
        date: "24/01/24",
        minSize: null,
        maxSize: null,
        fixedSize: 1,
        fee: 600,
        location: "",
    }
]